[install]
# Only install package versions published at least 7 days ago
minimumReleaseAge = 604800
# These packages will bypass the minimum age requirement
minimumReleaseAgeExcludes = ["@jsr/targoninc__jess", "@targoninc/jess-components", "@targoninc/lyda-shared", "@types/bun"]